repos:
  - repo: https://github.com/qiaojunfeng/pre-commit-julia-format
    rev: v0.2.1                # use the most recent version
    hooks:
    - id: julia-format         # formatter for Julia code
