name = "PMFRG_xyz"
uuid = "785b06fc-d355-4226-8a27-57b35e93bce2"
authors = ["Noah Hassan <noah01@zedat.fu-berlin.de>"]
version = "0.1.0"

[deps]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpinFRGLattices = "053fb7f8-31b7-4f68-aef8-4452b415dd8c"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Unroll = "36e64239-2ab9-4580-84fb-56737a503d36"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
