[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
FlameGraphs = "08572546-2f56-4bcf-ba4e-bab62c3a3f89"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LIKWID = "bf22376a-e803-4184-b2ed-56326e3bff83"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
PMFRG_xyz = "785b06fc-d355-4226-8a27-57b35e93bce2"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
ProfileSVG = "132c30aa-f267-4189-9183-c8a63c7e05e6"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SpinFRGLattices = "053fb7f8-31b7-4f68-aef8-4452b415dd8c"
ThreadPinning = "811555cd-349b-4f26-b7bc-1f208b848042"
Unroll = "36e64239-2ab9-4580-84fb-56737a503d36"
